# Generated by Django 3.2.4 on 2021-06-27 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ChatStore', '0002_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='room_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='room_msg', to='ChatStore.room'),
        ),
    ]
