# Generated by Django 3.2.4 on 2021-06-28 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatStore', '0003_messages_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
